## RSA - The Project

This project will guide you through the steps of code breaking using RSA (named after the three inventor's initials.) You will be able to encode your own message, decode someone else's message, and crack the code of someone else's private keys. As you follow along, you will start with  an essential function named FME (Fast Modular Expression), which is an algorithm to prepare your message for encryption and decryption. You will use this function later on when you get to the encode and decode section. The Euclidean Algorithm function will be used to create your public key, and the extended euclidean algorithm will be used to create your private keys. These two pieces of information are crucial to the success of the process. Once you have this information, you can input them into the encode/decode functions to reveal or encode the secret messages. You will also learn about prime factorization in the RSA process, which will round out the knowledge needing for understanding cryptography. Once you have gone through all the functions individually, you will have the chance at the end to use the guided interaction to encode and decode your own messages easily. You can create new keys, encode your own message, and decode a message whether you know the private key or not. 

In [2]:
def FME(b, n, m):
    result = 1 # This variable will be updated during the while loop, the if first condition is met 
    square = b # This variable will be updated with every iteration of the while loop
    while n > 0:
        k = n % 2 # Check if the n argument has a remainder after dividing it by 2 (next line)
        if k == 1: # Check if n mod 2 equals 1
            result = (result * square) % m #updates result when k equals 1
        square = (square * square) % m # square the base and take the mod with each iteration
        n = n // 2 # with every iteration, change the value of n to perform floor divison 
    return result
   

In [3]:
def Euclidean_Alg(a, b):
    if a <= 0 or b <= 0: # Add a check to ensure the inputs are postive numbers 
        return False
    while b > 0: # We will only run this loop until the second argument is smaller than 1
        k = a % b # Find a mod b
        a = b # Set a equal to the initial value of b
        b = k # set b equal to the value of k - This will be updated every loop
    return a
   

In [4]:
def EEA(a, b):
    if a <= 0 or b <= 0: # Add a check to ensure the inputs are postive numbers 
        return False
    m0, n0 = a, b # Define variables that will updated copies of a and b, but not the originals
    s1, t1 = 1, 0 # coeffients for a
    s2, t2 = 0, 1 # coeffients for b

    while n0 != 0:
        q = m0 // n0 # Find the quotient of m0 and n0
        m0, n0 = n0, m0 - q * n0 # Update using the remainder of the division above
        s1, s2 = s2, s1 - q * s2 # update coeffiennts for a
        t1, t2 = t2, t1 - q * t2 # update coefficients for b

    return m0, s1, t1
      
    
    

In [5]:
def Find_Public_Key_e(p, q):
    n = p * q # each individual has an encryption key (n, e) where n = pq
    find_e = (p - 1) * (q - 1) # # and an exponent e that is relatively prime to (p − 1)(q − 1)
    e = 2 # Start e at a given number
    # e = Euclidean_Alg(find_e, ea_gcd)
    # If e & ea_gcd == 1 & !== 9 | q 
    while e < find_e:
        if Euclidean_Alg(e, find_e) == 1 and e != p and e != q:
            return n, e # Loop will end once if satifies the condition that the gcd of e and find_e equals 1 and does not equal either of the two arguments
        e += 1 # add 1 to e until the condition is met, checking all possibilites 
    


In [6]:
def Find_Private_Key_d(e, p, q):
    n = (p - 1) * (q - 1) # Calculate 
    coefficients = EEA(e, n) # Use Extended Euclidean Algorithm to find coefficients
    d = coefficients[1] % n # Ensure d is positive and less than n above
    return d

  

In [7]:
def Convert_Text(_string):
    integer_list = []
    for i in _string:
        integer_list.append(ord(i))
    return integer_list

In [8]:
def Convert_Num(_list):
    _string = ''
    for i in _list:
        _string += chr(i)
    return _string

In [9]:
def Encode(n, e, message):
    encode_message = Convert_Text(message)
    cipher_text = [] # Empty list to hold the values converted into integers
    for i in encode_message: # for each letter in the message
        cipher_text.append(FME(i, e, n)) # run that converted integer plus the first two arguments through the FME function and add result to list
    return cipher_text

In [10]:
def Decode(n, d, cipher_text):
    message = ''
    decoded_message = []
    for i in cipher_text: # decrypt each cipher text using our Fast Modular Expression function
        decoded_message.append(FME(i, d, n))
    message = Convert_Num(decoded_message) # Convert decrypted numbers back to actual words
    return message

In order to generate an encoded message, you need to have two valuable pieces of information: n and e. The third piece of information will be the words you want encoded. In order to calculate n and e, you will use the Find_Public_Key_e function, adding two prime numbers of your choosing as the arguments:

In [11]:
def Find_Public_Key_e(p, q):
        n = p * q
        e = 2
        find_e = (p - 1) * (q - 1)
        while e < find_e:
            if Euclidean_Alg(e, find_e) == 1 and e != p and e != q:
                return n, e
            e += 1
            
Find_Public_Key_e(79, 89)

(7031, 5)

The function above uses another function, Euclidean_Alg, to calculate the GCD of the two primes you chose as arguments. In order to find the private key, which someone will need in order to decode, you will need  3 arguments: the 'e' that is returned from the public key function above, and the two prime numbers you chose previously. 

In [12]:
def Find_Private_Key_d(e, p, q):
    n = (p - 1) * (q - 1)
    coefficients = EEA(e, n)
    d = coefficients[1] % n
    return d

Find_Private_Key_d(5, 79, 89)

1373

The EEA function that is used above returns the GCD of the 'e' value you found in the public key function and value of , which is (p - 1) * (q - 1) (p and q being the two prime numbers you chose.) This function allows us to find the modular inverse of e mod n. The inverse if the private key that s being returned (d), which is essential in decoding a message. You can view that function below:

In [13]:
def EEA(a, b):
    m0, n0 = a, b
    s1, t1 = 1, 0
    s2, t2 = 0, 1

    while n0 != 0:
        q = m0 // n0
        m0, n0 = n0, m0 - q * n0
        s1, s2 = s2, s1 - q * s2
        t1, t2 = t2, t1 - q * t2

    return m0, s1, t1

Once you have the keys, you can encode and decode messages! To encode, you will need the values that were returned to you from the Find_Public_Key_e function. 

In [14]:
def Encode(n, e, message):
    encode_message = Convert_Text(message)
    cipher_text = []
    for i in encode_message:
        cipher_text.append(FME(i, e, n))
    return cipher_text

Encode(7031, 5, "Hello World")

[494, 7019, 2433, 2433, 2579, 2500, 3617, 2579, 5440, 2433, 5568]

This will return a list of numbers, like this: [494, 7019, 2433, 2433, 2579, 2500, 3617, 2579, 5440, 2433, 5568]

You can see that we are calling two functions inside this function. The first one, Convert_Text, takes the message in words and will return the number value. The second, FME, is the Fast Modular Expression function. This function looks like this:

In [15]:
def FME(b, n, m):
    result = 1 
    square = b 
    while n > 0:
        k = n % 2 
        if k == 1: 
            result = (result * square) % m 
        square = (square * square) % m
        n = n // 2  
    return result

To decode a message, you need three things: the 'd' value from the private keyfunction (ours is 1373), the n value from our public key function (ours is 7031) and the decoded message. The function to decode will take the encoded message and break down reach individual number value. It will then convert the number into a letter, and reveal the value in words/letters. 

In [16]:
def Decode(n, d, cipher_text):
    message = ''
    decoded_message = []
    for i in cipher_text:
        decoded_message.append(FME(i, d, n))
    message = Convert_Num(decoded_message)
    return message

Decode(7031, 1373, [494, 7019, 2433, 2433, 2579, 2500, 3617, 2579, 5440, 2433, 5568])

'Hello World'

This will turn this: [494, 7019, 2433, 2433, 2579, 2500, 3617, 2579, 5440, 2433, 5568]
Into this: Hello World

In [23]:
def factorize(n):
    for i in range(2, n -1): # iterate from 2 to find a factor
        if n % i == 0:  # Check if i is a factor of n
            return i # Return the smallest factor if found
        return False # Return false if no factor is found

EXAMPLE:
n,e=559 ,5 #Public Key

Cipher:[417, 150, 457, 127, 24, 52, 457, 367, 511, 203, 24, 367, 511, 367, 457, 12, 234, 417, 20, 44, 457, 127, 24, 52, 457, 24, 448, 511, 457, 447, 511, 457, 426, 52, 314, 203, 234, 362

The first step is to put the value of n from a public code into the factorization function:

In [24]:
def factorize(n):
    for i in range(2, n-1):
        if n % i == 0:
            return i
    return False
print(factorize(559))

13


The result from this is the integer 13. From there, we get the value of n (559) divided by p (13), which gave us the integer 43. Then, we put these values into the find_private_key function, like so: 

In [25]:
 Find_Private_Key_d(5, 13, 43)

101

This gives us the value 101, which is the value needed for 'd' in the decode function. 

In [26]:
Decode(559, 101, [417, 150, 457, 127, 24, 52, 457, 367, 511, 203, 24, 367, 511, 367, 457, 12, 234, 417, 20, 44, 457, 127, 24, 52, 457, 24, 448, 511, 457, 447, 511, 457, 426, 52, 314, 203, 234, 362])

'if you decoded this, you owe me lunch!'

Which translates to: 'if you decoded this, you owe me lunch!

In [ ]:
def main():
    RSA_project()

if __name__ == "__main__":
    main
    
def get_primes():
    first_prime = int(input("Enter first prime number"))
    second_prime = int(input("Enter second prime number"))
    return first_prime, second_prime

def get_keys(first_prime, second_prime):
    public_keys = Find_Public_Key_e(first_prime, second_prime)
    private_keys = Find_Private_Key_d(public_keys[1], first_prime, second_prime)
    print()
    print('************************')
    print()
    print('Public Keys: ', 'n: ', public_keys[0], 'e: ', public_keys[1])
    print('Private Key: ', private_keys)
    print()
    print('************************')
    print()
    return public_keys, private_keys
    
def get_user_choice():
    user_choice = input("""
    What would you like to do?
    1) Get new keys
    2) Encode a message
    3) Decode a message
    4) Quit program
    """)
    return user_choice

def RSA_project():
    while True:
        user_choice = get_user_choice()

        if user_choice == '1':
            first_prime, second_prime = get_primes()
            public_keys, private_keys = get_keys(first_prime, second_prime)
        elif user_choice == '2':
            n = input("Enter public key 'n': ")
            e = input("Enter public key 'e' : ")
            message = input("Enter message you would like to decode")
            encoded_message = Encode(int(n), int(e), message)
            print("cipher text: ", encoded_message)
        elif user_choice == '3':
            user_q = input("Do you know the private key? Please enter 'yes' or 'no'")
            if user_q == 'no':
                n = int(input("Enter public key 'n': "))
                e = int(input("Enter public key 'e': "))
                decode_message = input("Enter cipher text without the brackets, separated by commas")
                decoded_msg = decode_message.split(',')
                decode_elements = []
                for i in decoded_msg:
                    decode_elements.append(int(i))
                factorized = factorize(n)
                q = n / factorized
                find_private_key = Find_Private_Key_d(e, factorized, q)
                decoded_message = Decode(n, find_private_key, decode_elements)
                print("This message says: ", decoded_message)
            elif user_q == 'yes':
                n = int(input("Enter public key 'n': "))
                d = int(input("Enter private key"))
                decode_message = input("Enter cipher text without the brackets, separated by commas")
                decoded_msg = decode_message.split(',')
                decode_elements = []
                for i in decoded_msg:
                    decode_elements.append(int(i))
                decoded_message = Decode(n, d, decode_elements)
                print("This message says: ", decoded_message)
        elif user_choice == '4':
                print('Thanks for playing!')
                break
    
main()